### ISSUE TITLE
Unable to install todo editor on eclipse helios

### ISSUE THREAD

**Issue by utsengar** [sebastianbenz/eclipse-task-editor#10]
I have installed xText, but I get this error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Todo editor 1.0.1.201107241323 (de.sebastianbenz.task.feature.group 1.0.1.201107241323)
  Missing requirement: de.sebastianbenz.task.ui 1.0.1.201107241323 (de.sebastianbenz.task.ui 1.0.1.201107241323) requires 'bundle org.eclipse.ui.workbench.texteditor 3.7.0' but it could not be found
  Cannot satisfy dependency:
    From: Todo editor 1.0.1.201107241323 (de.sebastianbenz.task.feature.group 1.0.1.201107241323)
    To: de.sebastianbenz.task.ui [1.0.1.201107241323]

Any suggestions?

**Comment by sebastianbenz** [comment]
It seems like somehow a dependency to eclipse indigo sneaked in. I made a rebuild of the update site without the dependencies. It works now.
