### ISSUE TITLE
mvn build of rcp application failed

### ISSUE THREAD

**Issue by rs102** [sebastianbenz/eclipse-task-editor#18]
Following the isntructions to build the rcp application, results in a build failure. The artifact de.sebastianbenz.task.target could not be found.  This issue is that the parent pom specified version 1.0.0-SNAPSHOT in the tycho target definition. After I changed this to 1.0.2-SNAPSHOT to be consistent with what is being built, the build ran.

New target def:

```
      <resolver>p2</resolver>
      <target>
        <artifact>
          <groupId>de.sebastianbenz.task</groupId>
          <artifactId>de.sebastianbenz.task.target</artifactId>
          <version>1.0.2-SNAPSHOT</version>
          <classifier>indigo</classifier>
        </artifact>
      </target>
```

**Comment by sebastianbenz** [comment]
Thanks for letting me know!
