### ISSUE TITLE
Outline branch

### ISSUE THREAD

**Issue by DaneelReventelov** [sebastianbenz/eclipse-task-editor#19]
In Outline window the leaf tasks are marked as expandable with the arrow that disappears clicking on it

**Comment by sebastianbenz** [comment]
I cannot reproduce this problem. Do you have an example project with steps to reproduce?

**Comment by DaneelReventelov** [comment]
Test:
    Inner Test:
        -Task @done

The arrow appears when I add @done and then save. 
I don't know if can be the problem but if you change font and color there is a strange behavior of @done function.
In preference, with the others, there are three voice:
- Task open (without effect) (e.g. Violet)
- Task closed (@done) (e.g. Green)
- Default (all task) (e.g. Red)
  - This is a task (color Red)
  - This is a task closed @done (Green but the letter d of closed word remain Red)
    If you change the font size is more evident, for me task closed is very little and task open is large so the "d" is like a punch in the eye (a saying of my country :) )
