### ISSUE TITLE
Multi-line expandable task

### ISSUE THREAD

**Issue by DaneelReventelov** [sebastianbenz/eclipse-task-editor#22]
Can you add multi-line task? Now A task is only on one row but if I want a better description I must add a comment without @done function. Expandable/compressible can be better.

**Comment by sebastianbenz** [comment]
You could add a comment to your task with indendation, e.g.:
- a task @done
  some comments to the task

In that case the @done tag applies to the task and to the note.

Another possibility would be to add an escape character (e.g. ) to the line ending:
- a multiline task\
   this is the second line

But I am not sure whether this is really necessary.

**Comment by DaneelReventelov** [comment]
At the start I wrote many things in a task but now I write only a title and then the specify instructions in java comment so for now I think this problem for me is surpassed
