### ISSUE TITLE
SubTask style

### ISSUE THREAD

**Issue by DaneelReventelov** [sebastianbenz/eclipse-task-editor#23]
Now there are 
 -Project in bold and magnified
 -Sub-project in bold and less magnified of the project 
 -Task not bold
 -Sub Task Set( -I am a sub-task set: ) like a task 

Can you change sub task set font in bold?

**Comment by sebastianbenz** [comment]
I think that would make the syntax highlighting too confusing. If you want to achieve a visual separation I would recommend to use projects. Now that projects are also marked as done via strikethrough this should be no problem.

**Comment by DaneelReventelov** [comment]
Ok, you're right
