### ISSUE TITLE
@Done for entire branch

### ISSUE THREAD

**Issue by DaneelReventelov** [sebastianbenz/eclipse-task-editor#27]
Can you add @Done tag for entire branch. Now adding @done near branch title have a strange behavior, gray strike-through text without changing son so there are only 3 way:
- 1 @done near title add automatic @done  to all is sons
- 2 @done change text style to strike-through for title and sons
- 3 @done is marked as error

I prefer 2 to permit Undo too difficult for 1

**Comment by sebastianbenz** [comment]
I also think solution 2 makes the most sense. Thanks for the suggestion.

**Comment by DaneelReventelov** [comment]
Great, Thanks
