### ISSUE TITLE
Xtext nature for src/bin

### ISSUE THREAD

**Issue by DaneelReventelov** [sebastianbenz/eclipse-task-editor#28]
When I create a new Project, Eclipse ask me to chose between to option:
- Use project folder as root for sources and class files (I use this in my previous project last year)
- Create separate folders for sources and class files (Eclipse default. Now I chose this for many reason)

If I use first option, when I create a .todo file a message box appears asking me if I want Xtext Nature and the query works.
If I use separate folder, when I create .todo file no message box appears. The .todo editor works and query not. 
In builder option area xtext builder is selected and .todo file is built in bin folder so query don't work,

**Comment by DaneelReventelov** [comment]
I'm looking for a solution and I tried many possibility:
- Added a new build path only for .todo file with an own output folder so I have 3 test area:
         - Main project folder
         - Src folder
         - Todo folder (src e built file)
- Found Xtext nature option and Xpand nature option
- Test:
  1: 3 .todo file created in every folder without xtext and xpand natures, natures activated = Not works  
  2: 3 .todo file created in every folder with xtext and xpand natures = Not works  
  3: 3 .todo file created in every folder with xtext nat. and without xpand nat. = Not works, xpand activated= Not Work 
  4: The third point but viceversa 
  1,2,3,4 bis: For every new test retested old file= Not Work

**Comment by sebastianbenz** [comment]
Is it possible that you todo file's have an extension in mixed case (e.g. _.Todo,_.TODO)? Xtext currently does only index files if their extension is written in lower case, which would cause the file not being shown in the query view.

**Comment by DaneelReventelov** [comment]
For consistency and coherence I use only lover case for extension, however I create a project in a clean and new workspace area without separate folders and works from first moment.

Off topic. Excuse me if I bother you with so many issues. I know the major part of programmers consider own creation as son and don't accept suggestion so, please, don't be angry, I appreciate your add-on very much and I search it for a long time so I ask you to improve it in order to join my necessity but if my request are presumptuous please say me and I immediately stop. Thanks

**Comment by DaneelReventelov** [comment]
And now the very strange things: Upgrading syntax in my project to new Java 7 "try" system I discover Indigo 3.7 official don't support new syntax so I download the latest 3.7 build, 3.8 build and 4.2 build. 
Incredibly 4.2 support all addon I use but the first time Todo query doesn't works, instead from second restart it works.
This is very strange, in the next few day I'll try last 3.7 and 3.8.
