### ISSUE TITLE
Font option normalization

### ISSUE THREAD

**Issue by DaneelReventelov** [sebastianbenz/eclipse-task-editor#29]
In preference there are contrasting item with the same title "task". Can you can your label to exemplify their better (e.g. Xtext Task)?
Now Xtext Task use own font pointer, can you move to "Fonts and Colors" in Windows->preference->general->Appearance-> so other add-on can act simultaneously like "eclipse-fonts" to change size for my poor eyes and maybe also color-theme addon

**Comment by sebastianbenz** [comment]
This would be difficult to change, as it is the default behavior of xtext. But finding better names for the different tasks should be no problem.

**Comment by DaneelReventelov** [comment]
It's a pity, I like enlarge and reduce font to have an overview or a focused area and Eclipse-font work only on inner font repository. However different name is a great improvement to not confuse with Mylyn.

**Comment by sebastianbenz** [comment]
I renamed the preference page to Todo Editor and also improved the identifiers of the different syntactic elements.

**Comment by DaneelReventelov** [comment]
Good, I'll wait for eclipse update site release :)
