### ISSUE TITLE
cannot be installed because of XText

### ISSUE THREAD

**Issue by anb0s** [sebastianbenz/eclipse-task-editor#31]
I cannot install with gived update site, because XText cannot be found. Need detailed installation description how to resolve XText dependency. Thanks!

**Comment by anb0s** [comment]
See also error report from Marketplace (http://marketplace.eclipse.org/content/eclipse-todo-editor/error_reports)
...
Cannot complete the install because one or more required items could not be found. Software being installed: Todo editor 1.1.0.201112202244 (de.sebastianbenz.task.feature.group 1.1.0.201112202244) Missing requirement: de.sebastianbenz.task 1.1.0.201112202244 (de.sebastianbenz.task 1.1.0.201112202244) requires 'bundle org.eclipse.xtext 2.2.1' but it could not be found Cannot satisfy dependency: From: Todo editor 1.1.0.201112202244 (de.sebastianbenz.task.feature.group 1.1.0.201112202244) To: de.sebastianbenz.task [1.1.0.201112202244]
...

Other users have same problem, maybe the information about adding XText update site first "http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/" and select "Contact all update sites..." will help.

**Comment by sebastianbenz** [comment]
Thanks for letting me know. There was a problem in the update site. The update site should now also include the xtext artifacts.

**Comment by anb0s** [comment]
It works now! Thanks!
