### ISSUE TITLE
ID not takes unique values

### ISSUE THREAD

**Issue by rahulsmitsonian** [sebastianbenz/eclipse-task-editor#34]
I downloaded my version directly from the itemis-xtext site:
  http://xtext.itemis.com/xtext/language=en/36553/downloads
  eclipse-SDK-3.7.1-Xtext-2.2.1-win32.zip

I am facing a very weird problem. The Terminals ID does not seem to be working. e.g. In my grammar if I declare 

Model:
      greetings+=Greeting*;

Greeting:
      'Hello' name=ID '!';

Then in the editor I can have

Hello Name !
Hello Name !
Hello Name !

It does not show any error, even  if same ID is used at more than one places. This problem was not present in 1.x versions.

**Comment by sebastianbenz** [comment]
This looks like a xtext problem. The xtext newsgroup is the right place for these questions:

http://www.eclipse.org/forums/index.php?t=thread&frm_id=27
