### ISSUE TITLE
Need a way to disable "unknown language" warnings (or define languages)

### ISSUE THREAD

**Issue by PerMildner** [sebastianbenz/eclipse-task-editor#36]
I use the ''' quoting for code snippets that are not Java. This gets marked with a warning "Unknown language" which is annoying.

It would be nice to be able to define new languages, and to be able to turn off the warning.

**Comment by sebastianbenz** [comment]
You don't get a warning if you add a line break after the starting '''. For example:

'''Hello World
'''
gives a warning but:
'''
Hello World // no warning
'''
doesn't. 

It is quite easy to add syntax highlighting support for further languages. Which languages are missing? You can have a look here to see how to add more languages: 

https://github.com/sebastianbenz/eclipse-task-editor/blob/master/plugins/de.sebastianbenz.task.ui/src/de/sebastianbenz/task/ui/highlighting/BrushRegistry.java

**Comment by PerMildner** [comment]
That explains it, I tried to use it for in-line code snippets, something like [some text '''...some code...''' some more text]

(The language was Prolog but I have no need for syntax highlighting in the my TODOs.)
