### ISSUE TITLE
mvn clean install fails on linux x86_64

### ISSUE THREAD

**Issue by jvb** [sebastianbenz/eclipse-task-editor#40]
First building the tests and then building the rcp.

My solution (Jon) can be found here: http://stackoverflow.com/questions/9405802/eclipse-product-invocation-causes-classnotfoundexception-of-org-eclipse-swt-swte/9703330#9703330

I'm sure this was not the best workaround, but when it didn't comment out the other environments it tried (and predicably failed) to build the macosx binary!

**Comment by jvb** [comment]
I also had to add the following to plugins/de.sebastianbenz.task.platform-feature/feature.xml to get it to run on linux x86_64:

   <plugin
         id="org.eclipse.swt.gtk.linux.x86_64"
         download-size="0"
         install-size="0"
         version="0.0.0"
         fragment="true"
         unpack="false"/>

**Comment by sebastianbenz** [comment]
I have just added linux x86_64 as a build environment. Could you please verify whether it works now for you?

**Comment by jvb** [comment]
Hi. In a fresh clone I ran mvn clean install and got the following:

[INFO] --- tycho-p2-director-plugin:0.13.0:materialize-products (materialize-products) @ de.sebastianbenz.task.rcp ---
[INFO] Calling director with arguments: [-metadatarepository, file:/home/jvb/git/new/plugins/de.sebastianbenz.task.rcp/target/publisherRepository/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task.edit/target/,file:/home/jvb/git/new/features/de.sebastianbenz.task-feature/target/,file:/home/jvb/git/new/features/de.sebastianbenz.task.platform-feature/target/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task.ui/target/,file:/home/jvb/git/new/features/de.sebastianbenz.task.rcp-feature/target/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task.application/target/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task/target/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task.rcp/target/targetPlatformRepository/, -artifactrepository, file:/home/jvb/git/new/plugins/de.sebastianbenz.task.rcp/target/publisherRepository/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task.edit/target/,file:/home/jvb/git/new/features/de.sebastianbenz.task-feature/target/,file:/home/jvb/git/new/features/de.sebastianbenz.task.platform-feature/target/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task.ui/target/,file:/home/jvb/git/new/features/de.sebastianbenz.task.rcp-feature/target/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task.application/target/,file:/home/jvb/git/new/plugins/de.sebastianbenz.task/target/,file:/resolution-context-artifacts@/home/jvb/git/new/plugins/de.sebastianbenz.task.rcp,file:/home/jvb/.m2/repository/, -installIU, task-editor, -destination, /home/jvb/git/new/plugins/de.sebastianbenz.task.rcp/target/products/task-editor/macosx/cocoa/x86_64/task-editor, -profile, DefaultProfile, -profileProperties, org.eclipse.update.install.features=true, -roaming, -p2.os, macosx, -p2.ws, cocoa, -p2.arch, x86_64]
Installing task-editor 1.1.1.201203141602.
Installation failed.
An error occurred while installing the items
 session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]task-editor.executable.cocoa.macosx.x86_64 1.1.1.201203141602, action=org.eclipse.equinox.internal.p2.touchpoint.natives.actions.ChmodAction).
 The action chmod failed - file /home/jvb/git/new/plugins/de.sebastianbenz.task.rcp/target/products/task-editor/macosx/cocoa/x86_64/task-editor/eclipse.app/Contents/MacOS/eclipse does not exist
Application failed, log file location: /home/jvb/git/new/workspace/.metadata/.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Task Editor Runtime ............................... SUCCESS [7.141s]
[INFO] Task Editor Edit .................................. SUCCESS [1.189s]
[INFO] Task Editor UI .................................... SUCCESS [2.292s]
[INFO] Task RCP Application .............................. SUCCESS [1.051s]
[INFO] Task Editor Tests ................................. SUCCESS [19.551s]
[INFO] Task Editor RCP Feature ........................... SUCCESS [0.592s]
[INFO] Task Editor Feature ............................... SUCCESS [0.511s]
[INFO] Task Editor RCP Platform Feature .................. SUCCESS [0.681s]
[INFO] Task Editor RCP Product ........................... FAILURE [14.333s]
[INFO] Plugins ........................................... SKIPPED
[INFO] Features .......................................... SKIPPED
[INFO] Task Editor Target Definition ..................... SKIPPED
[INFO] Todo Editor ....................................... SKIPPED
[INFO] Tools ............................................. SKIPPED
[INFO] RCP Parent ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:01.368s
[INFO] Finished at: Wed Mar 14 16:03:02 GMT 2012
[INFO] Final Memory: 101M/415M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:0.13.0:materialize-products (materialize-products) on project de.sebastianbenz.task.rcp: P2 director return code was 13 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :de.sebastianbenz.task.rcp

**Comment by sebastianbenz** [comment]
This looks like this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=349877 . I upgraded to tycho 0.14.1 and set a custom launcher name (which finally works with tycho). Could you please verify again?

**Comment by jvb** [comment]
Maven finishes successfully and ./plugins/de.sebastianbenz.task.rcp/target/products/task-editor/linux/gtk/x86_64/task-editor/taskeditor runs OK. Thank you.

I am making an Xtext-based RCP app too so it is invaluable being able to see you code. And now I'm using eclipse-task-editor too.

**Comment by sebastianbenz** [comment]
Thanks for the feedback!
