### ISSUE TITLE
Could not open the editor: Editor could not be initialized.

### ISSUE THREAD

**Issue by trenchcode** [sebastianbenz/eclipse-task-editor#8]
I haven't been able to make this run so far. I get the following error using a fresh install of Eclipse Indigo and only the plugins Xtext and Task Editor installed:

`org.eclipse.xtext.parser.ParseException: java.lang.IllegalStateException: Unresolved proxy http://www.sebastianbenz.de/task/2011/#//TaskModel. Make sure the EPackage has been registered.`

Any ideas how this can be fixed?

**Comment by sebastianbenz** [comment]
Sorry about that. It's fixed now. I didn't notice that because I also had an older version installed. Thanks for reporting!
