### ISSUE TITLE
Query problems

### ISSUE THREAD

**Issue by trenchcode** [sebastianbenz/eclipse-task-editor#9]
I installed the latest version and queries did not work until I built the project with Xtext. Now it seems that queries are still not working properly. Querying @todo and @done doen't give any results. Phrase search is working though. Can you confirm this behavior?

**Comment by sebastianbenz** [comment]
Hm, I can't reproduce this. Try performing a clean, maybe the index got somehow corrupted. One thing is that queries search only through the saved version of a file.

**Comment by trenchcode** [comment]
Here's what I figured out:
- The index updates only if I close the query view and reopen it. Saving the file or cleaning/rebuilding the project doesn't update the index.
- queries (@tags, phrase search etc.) work only with level one tasks, not with subtasks (> level 2)

**Comment by sebastianbenz** [comment]
- This shouldn't be the case. The view is updated after every file change. Are you sure that your project has the xtext nature? I can't reproduce this error.
- That's true. Currently only nested projects are supported. This restriction is a remainder of a previous version were it didn't support nesting tasks at all, but this doesn't make sense anymore. I will fix that.

**Comment by trenchcode** [comment]
Okay, I turned on "build automatically" and the view updates after every file change now.

The other point would be nice to have and would make the editor even more useful. Btw, thank you for this great and promising project, much needed on the Eclipse platform!

**Comment by sebastianbenz** [comment]
Its fixed in the trunk. Thanks for your feedback!

**Comment by sebastianbenz** [comment]
Is now also available via the update site.
